name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build gcc g++ libglfw3-dev

    - name: Configure with CMake
      run: cmake -S Engine -B build -G "Ninja"

    - name: Build with Ninja
      run: cmake --build build
