name: Build and Test

on:
  push:
    branches:
      - main    # Run the workflow on pushes to the main branch
  pull_request:  # Run the workflow for pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build gcc g++ libglfw3-dev

    # Step 3: Configure CMake
    - name: Configure with CMake
      run: |
        cmake -S Engine -B build -G "Ninja"

    # Step 4: Build the project
    - name: Build with Ninja
      run: cmake --build build

    # Step 5: Run tests (optional)
    - name: Run Tests
      run: ctest --test-dir build
